//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargoSirketiProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kargolar
    {
        public int KargoId { get; set; }
        public Nullable<int> KargoPrID { get; set; }
        public Nullable<System.DateTime> KargoAlımTarih { get; set; }
        public Nullable<System.DateTime> KargoTeslimTarih { get; set; }
        public Nullable<int> KargoDurumId { get; set; }
        public string KargoNot { get; set; }
        public string KargoAdres { get; set; }
        public string KargoBaslik { get; set; }
    
        public virtual KargoDurum KargoDurum { get; set; }
        public virtual Personeller Personeller { get; set; }
    }
}
