//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargoSirketiProjesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KargoSirketiDBEntities : DbContext
    {
        public KargoSirketiDBEntities()
            : base("name=KargoSirketiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KargoDurum> KargoDurum { get; set; }
        public virtual DbSet<Kargolar> Kargolar { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<Subeler> Subeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
    }
}
