//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargoSirketiProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Kargolar = new HashSet<Kargolar>();
        }
    
        public int PrId { get; set; }
        public string PrAdSoyad { get; set; }
        public string PrKullanici { get; set; }
        public string PrSifre { get; set; }
        public Nullable<int> PrSubeId { get; set; }
        public Nullable<int> PrYetkiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kargolar> Kargolar { get; set; }
        public virtual Subeler Subeler { get; set; }
        public virtual Yetkiler Yetkiler { get; set; }
    }
}
